<?php
session_start();
if(isset($_SESSION['login_user']))
{
    unset($_SESSION['login_user']);
}
if(isset($_SESSION['login_user_admin']))
{
    unset($_SESSION['login_user_admin']);
}
session_destroy();
header('location:login.php');
?>